### PR TITLE
241 add model for speaking practice sessions

### PR DESCRIPTION
**Pull request by aedmondson**
Note that this is not pulling into Placeholder-Pages. This should be reviewing schema, not integration.

### CODE REVIEW

**Comment by aedmondson** [comment]
Converted to draft because I need to write migrations

**Comment by aedmondson** [comment]
**BEFORE APPROVING**: test the migrations.
To test the migrations:
1. Copy all `.sqlite3` files from your project root to another place outside project to back them up. **DO NOT SKIP THIS STEP**
2. Checkout `Placeholder-Pages` and git pull.
3. Run the server and visit `http://127.0.0.1:8000/admin/ComSemApp/speakingpracticeattempt/`
4. Scroll to the bottom and _screenshot_ the window, including total number of attempts and a few entries above the count.
5. Shut down the server
6. Checkout `241-add-model-for-speaking-practice-sessions` and git pull
7. In your project's root directory, run the following command `python manage.py migrate`. If your migration fails, screenshot the entire output of the command, place it in a comment, and request changes.
8. Run the server and visit `http://127.0.0.1:8000/admin/ComSemApp/speakingpracticeattempt/`
9. Scroll to the bottom and _screenshot_ the window, including total number of attempts and a few entries above the count.
10. Shut down the server
11. Checkout Placeholder-Pages
12. Copy your backed-up `.sqlite3` files into your project's root directory
13. Upload your screenshots into a comment on this pull request
14. If the count of SpeakingPracticeAttempts differs before and after the migration, request changes.

**Comment by dpmacisaac** [comment]
Screenshot from 2023-03-28 16-29-31
Screenshot from 2023-03-28 16-28-18

Seems like it went well. Attempts match up and data seems correct

**Comment by dpmacisaac** [comment]
You can see above that one expression is in the same session twice (session 46), that might be something that you want to change in the migration but it might not be terribly important

**Comment by aedmondson** [comment]
> You can see above that one expression is in the same session twice (session 46), that might be something that you want to change in the migration but it might not be terribly important

I'll fix this. It should be organized as such so other pages don't encounter errors with it.

**Review by Jared-Torii — DISMISSED** [review]
look fine to me.

**Review by dpmacisaac — APPROVED** [review]
i re-ran the update and it work. Sessions look good now and don't have repeating expressions in each session

**Review by dpmacisaac — APPROVED** [review]

**Review by zambroseo — APPROVED** [review]
attempts shot2
attempts shot

**Pull request merged**
